config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#top"
  get '/home/about', to: 'home#about', as: 'about'
  resources :books, only: [:show, :index, :edit, :create, :update, :destroy]
  resources :users, only: [:show, :index, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, :body, presence: true
  validates :body, length: {in: 2..200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :books, dependent: :destroy
  has_one_attached :user_image
  validates :name, presence: true, length: {in: 2..20}, uniqueness: true
  validates :introduction, length: { maximum: 50 }
  
  def get_user_image(width, height)
    unless user_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      user_image.attach(io: File.open(file_path), filename:'default-image.jpg', content_type:'image/jpeg')
    else
      user_image.variant(resize_to_limit:[width, height]).processed
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :comfigure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:top, :about]

  def after_sign_in_path_for(resource)
    @user = 
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def shared_path
    @post = Book.new
    @user = User.find(current_user.id)
  end

  def comfigure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:email])
  end

  def seve_clear
    if @post.save
      flash[:notice] = "You have created book successfully"
      redirect_to book_path(@post.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end

  def update_clear
    if @post.update(book_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to book_path(@post.id)
    else
      render :edit
    end
  end

  def matched_login_use
    user_id = params[:id].to_i
    login_user_id = current_user[:id].to_i
    if (user_id != login_user_id)
      redirect_to user_path(current_user.id)
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    shared_path
  end

  def create
    @post = Book.new(book_params)
    @post.user_id = current_user.id
    seve_clear
  end

  def show
    shared_path
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def edit
    matched_login_use
    @post = Book.find(params[:id])
  end

  def update
    matched_login_use
    @post = Book.find(params[:id])
    update_clear
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def matched_login_use
    user_id = Book.find(params[:id]).user_id.to_i
    login_user_id = current_user.id.to_i
    if (user_id != login_user_id)
      redirect_to books_path
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    shared_path
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @users = User.all
    shared_path
  end

  def edit
    matched_login_use
    @post = User.find(current_user.id)
  end

  def update
    matched_login_use
    @post = User.find(params[:id])
    update_clear
  end

  private
    def user_params
      params.require(:user).permit(:name, :introduction, :user_image)
    end

    def update_clear
      if @post.update(user_params)
        flash[:notice] = "You have updated user successfully."
        redirect_to user_path(@post.id)
      else
        render :edit
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_title
    if @title.present?
      @title
    else
      @title = "New book"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<% @title = "Editing Book" %>
<main class="container">
  <div class="col-sm-8 col-md-6 col-lg-4 mx-auto">
    <%= render 'shared/form', post:@post, form_text: 'Update Book' %>
    <div>
      <%= link_to 'Show',book_path(@post.id) %>
      <span>|</span>
      <%= link_to 'Back', books_path %>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 mt-4">
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/profile', user:@user %>
        <%= render 'shared/form', post:@post, form_text: 'Create Book' %>
      </div>
      <div class="col-md-8 offset-md-1">
        <%= render 'shared/head' %>
            <% @books.each do |book| %>
              <tr>
                <%= render 'shared/table', book:book %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main class=" px-5 mt-4">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/profile', user:@user %>
        <%= render 'shared/form', post:@post,form_text:'Create Book' %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table mb-0">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user_id)  do %>
                  <%= image_tag @book.user.get_user_image(100,100) %>
                  <p class="mb-0 w-100"><%= @book.user.name%></p>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book.id) %></td>
              <td><%= @book.body%></td>
  
              <%= render 'shared/under', book:@book %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/home/about.html.erb
<main class="container px-5 mt-4">
  <div class="mx-auto col-9 col-sm-8 col-lg-7 col-xl-5 text-center">
    <h1>Welcome to
      <strong><i class="fas fa-book"></i> Bookers!</strong>
    </h1>
  </div>
</main>

app/views/home/top.html.erb
<main class="mt-4">
  <p class="text-center"><%= flash[:notice] %></p>
  <div class="container mt-2">
    <div class="row">
      <div class="mx-auto col-9 col-sm-8 col-lg-7 col-xl-5">
        <h1 class="text-center">Welcome to
          <strong><i class="fas fa-book"></i> Bookers!!</strong>
        </h1>
        <div class="col-10 mx-auto">
          <p>in
            <strong><i class="fas fa-book"></i> Bookers,</strong></p>
          <p>you can share and exchange your options, inpressions, and emotions</p>
          <p>about various books!</p>
        </div>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row mb-3">
            <%= link_to 'Log in', new_user_session_path, class:"btn btn-sm btn-info btn-block sign_in" %>
          </div>
          <div class="row mb-3">
            <%= link_to 'Sign up', new_user_registration_path, class:"btn btn-sm btn-success btn-block sign_up" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers", root_path, class:"navbar-brand text-light " %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarDropdown">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="p-2">
                <%= link_to user_path(current_user.id), class:"navbar-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li class="p-2">
                <%= link_to users_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-users"></i>
                  Users
                <% end %>
              </li>
              <li class="p-2">
                <%= link_to books_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-book-open"></i>
                  Books
                <% end %>
                </li>
                <li class="p-2">
                  <%= link_to destroy_user_session_path, method: :delete, class:"navbar-link text-light" do %>
                    <i class="fas fa-sign-out-alt"></i>
                    Log out
                  <% end %>
                </li>

            <% else %>
              <li class="p-2">
                <%= link_to root_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-home"></i>
                  Home
                <% end %>
              </li>
              <li class="p-2">
                <%= link_to about_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-link"></i>
                  About
                <% end %>
              </li>
              <li class="p-2">
                <%= link_to new_user_registration_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-user-plus"></i>
                  Sign up
                <% end %>
              </li>
              <li class="p-2">
                <%= link_to new_user_session_path, class:"navbar-link text-light" do %>
                  <i class="fas fa-sign-in-alt"></i>
                  Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <p class="mx-auto">CopyRight Infratop.inc</p>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/shared/_form.html.erb
<% if post.errors.any? %>
  <h4>error</h4>
  <ul>
    <% post.errors.full_messages.each do |message|%>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<h2 class="mt-4"><%= form_title %></h2>
<%= form_with model:post do |f| %>
  <div class="form-group mb-2">
    <%= f.label :title, class:"mb-1" %><br/>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group mb-3">
    <%= f.label :option, class:"mb-1" %><br/>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "#{form_text}", class:"btn btn-success" %>
  </div>
<% end %>

app/views/shared/_head.html.erb
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Option</th>
    </tr>
  </thead>
  <tbody>

app/views/shared/_profile.html.erb
<%= flash[:notice] %>
<h2>User info</h2>
<% if user.user_image.attached? %>
  <%= image_tag user.user_image.variant(resize_to_limit:[100,100]).processed %>
<% else %>
  <% file_path = Rails.root.join('app/assets/images/no_image.jpg')%>
  <% user.user_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg') %>
  <%= image_tag user.user_image%>
<% end %>
<table class="table mb-2">
  <tr>
    <th>name</th>
    <th><%= user.name %></th>
  </tr>
  <tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </tr>
</table>
<div class="row">
  <%= link_to edit_user_path(user.id),class:"btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/shared/_table.html.erb
<td>
  <%= link_to user_path(book.user_id)  do %>
    <%= image_tag book.user.get_user_image(100,100) %>
  <% end %>
</td>
<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body%></td>

app/views/shared/_under.html.erb
<% if book.user.id == current_user.id %>
  <td>
    <%= link_to 'Edit', edit_book_path(book.id), class:"btn btn-success btn-sm" %>
  </td>
  <td>
    <%= link_to 'Destroy', book_path(book.id), method: :delete, class:"btn btn-danger btn-sm", "data-confirm" => "本当に消去しますか?"%>
  </td>
<% end %>

app/views/users/edit.html.erb
<main>
  <div class="cotaner mt-4">
    <%= flash[:notice] %>
    <div class="row">
      <div class="col-sm-11 col-md-8 col-lg-5 mx-auto">
        <% if @post.errors.any? %>
          <h3><%= @post.errors.count %>件のエラー</h3>
          <ul>
            <% @post.errors.full_messages.each do |message|%>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <h2>User info</h2>
        <%= form_with model:@post, method: :put do |f| %>
          <div class="form-group">
            <%= f.label :Name, class:"mb-1" %><br/>
            <%= f.text_field :name, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Image, class:"mb-1" %><br/>
            <%= f.file_field :user_image, accept:"image/*" %>
          </div>
          <div class="form-group">
            <%= f.label :Introduction, class:"mb-1" %><br/>
            <%= f.text_area :introduction, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update User', class:"btn btn-secondary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main class="px-5 mt-4">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/profile', user:@user %>
        <%= render 'shared/form', post:@post, form_text: 'Create Book' %>
      </div>
      <div class="col-md-8 offset-md-1">
        <%= render 'shared/head' %>
          <% @users.each do |user| %>
            <tr>
              <td><%= link_to user_path(user.id) do%>
                <%= image_tag user.get_user_image(100,100) %>
                <% end %>
              </td>
              <td><%= user.name%></td>
              <td><%= link_to 'Show',user_path(user.id) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="container px-5 mt-4 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'shared/profile', user:@user %>
        <%= render 'shared/form', post:@post, form_text: 'Create Book' %>
      </div>
      <div class="col-md-8 offset-md-1">
        <%= render 'shared/head' %>
          <% @books.each do |book| %>
            <%= render 'shared/table', book:book %>
              <%= render 'shared/under', book:book %>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>